### ISSUE TITLE
71_clamav-0.103.5.update: no set_version execution and execution of update every time Updater4MC runs

### ISSUE THREAD

**Issue by Brauadler** [MailCleaner/Updater4MC#52]
@JohnMertz:
Hi John,
after the daily execution of Updater4MC the update of ClamAV was succesful on my server but the version of Mailcleaner wasn't raised to the new date. The version is still january. After checking todays log, i also noticed that 71_clamav-0.103.5.update was executed a second time without updating the files, because it was already down. There was no file to block that in /var/mailcleaner/spool/updater.

**71_clamav-0.103.5.update:**

![grafik](https://user-images.githubusercontent.com/95625809/156534013-45c2ed33-cffe-4418-92bf-18ed534d7748.png)

Is it possible that line 13 is never executed, because of the returns in the if...else statement ? Also after the succesfull upgrade of ClamAV the return code from **71_clamav-0.103.5.update** is **1** and if you go check the executing part in **Updater4MC.sh** neither  if...else statement is triggered.

**Updater4MC.sh (line 117-131):**

    if [ ! -e "${VARDIR}/spool/updater/$(basename -s'.update' ${updtfile})" ]; then
	echo "Executing update: $updtfile ..."
	. "$updtfile"
	retcode=$?
	if [ $retcode -eq 0 ]; then
	    touch "${VARDIR}/spool/updater/$(basename -s'.update' ${updtfile})"
	elif [ $retcode -ne 1 ]; then
	    echo -e "\tError during ${updtfile} update. Please join logfile to your post on MailCleaner Community forum."
            echo "Failed to complete update $updtfile" > $STATUSFILE
	    exit 1
	fi
	echo "End of update."
    else
	echo "Already updated: $updtfile ..."
    fi

**Comment by JohnMertz** [comment]
You are correct. Silly mistake, sorry. The next update should succeed.

**Comment by Brauadler** [comment]
Thank you for the quick fix. The patch level is now up to date and the file for the correctly executed update has been created.
