### ISSUE TITLE
E: The method driver /usr/lib/apt/methods/https could not be found.

### ISSUE THREAD

**Issue by Brauadler** [MailCleaner/Updater4MC#74]
Hello @JohnMertz, 
there were log entries in the updater4mc.log about an error with the method driver /usr/lib/apt/methods/https after the update 00 and 80.

> Executing update: /root/Updater4MC/updates/00_archive_repos.update ...
> Updating Repositories to use Archives
> E: The method driver /usr/lib/apt/methods/https could not be found.
> End of update.
> Already updated: /root/Updater4MC/updates/01_httpsgit.update ...
> [removed] ...
> Already updated: /root/Updater4MC/updates/79_ed25519.update ...
> Executing update: /root/Updater4MC/updates/80_ipset.update ...
> E: The method driver /usr/lib/apt/methods/https could not be found.
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package ipset
> End of update.

**Comment by JohnMertz** [comment]
Interesting. The package `apt-transport-https` should resolve this. It was my understanding that it had previously been installed by another update, but perhaps I'm mistaken.

I will modify the existing 00 update to use 'http', then add another update immediately after that to install `apt-transport-https`, then upgrade the repos to use 'https'. Any machines that have already run the existing 00 will then just install the package, but new machines will go through the whole procedure in a way that will not result in any errors. PR coming soon...

**Comment by JohnMertz** [comment]
Looks like it was only the docker repo that was using https, so I just removed it from the main sources list, then made a separate update where `apt-transport-https` gets installed first, then docker is given it's own sources file. Merged with #75

**Comment by Brauadler** [comment]
Now, unfortunately, there is another problem.
I manually deleted the "update completed" files for "00_archive_repos" and "80_ipset" in the spooler folder and let the Updater4mc.sh run through. The sourcelist was successfully adjusted and https removed, but now the "00_docker_repo.update" fails with the following problem and terminates the script. 

> Executing update: /root/Updater4MC/updates/00_archive_repos.update ...
End of update.
Executing update: /root/Updater4MC/updates/00_docker_repo.update ...
E: Unable to locate package apt-transport-https
/root/Updater4MC/updates/00_docker_repo.update: line 7: [: !-d: unary operator expected
E: The method driver /usr/lib/apt/methods/https could not be found.
	Error during /root/Updater4MC/updates/00_docker_repo.update update. Please join logfile to your post on MailCleaner Community forum.

**Comment by JohnMertz** [comment]
This should be fixed. You should not need to clear the flag for either 00_archive_repos or 80_ipset, but you will need to for 00_docker_repo, if it exists.

**Comment by Brauadler** [comment]
> Executing update: /root/Updater4MC/updates/00_docker_repo.update ...
E: The method driver /usr/lib/apt/methods/https could not be found.
E: Unable to locate package apt-transport-https
E: The method driver /usr/lib/apt/methods/https could not be found.
	Error during /root/Updater4MC/updates/00_docker_repo.update update. Please join logfile to your post on MailCleaner Community forum.

**Comment by JohnMertz** [comment]
Oh. I expect that the issue is that the /etc/apt/sources.list.d/docker.list file already exists. The patch I just made should work for someone who has not tried to install the most recent update file at all, but since you already had, the 'apt-get update' is still trying to fetch from that repo. If you `rm /etc/apt/sources.list.d/docker.list`, then repeat the last install attempt, it should work.

**Comment by Brauadler** [comment]
In the meantime, I have also decided to delete the docker.list manually as you have posted. I can contribute the following information for further installation:
The following warning exists for 00_docker_repo.update and 80_ipset ...
W: GPG error: http://archive.debian.org jessie Release: The following signatures were invalid: KEYEXPIRED 1587841717
Otherwise everything seems to have worked. Thank you.

**Comment by JohnMertz** [comment]
There is unfortunately nothing that we can do about the expired GPG key. We'll starting open alpha testing of the next major release, based on Debian Bookworm, which will get as away from this whole repository archive problem and it should come pre-configured with the https support and docker repo.

In the meantime, I thank you for your help!
